language: java
dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

after_success:
  - ./gradlew cobertura pitest coveralls -Pbintray_user="" -Pbintray_apikey=""

install:
  - ./gradlew assemble -Pbintray_user="" -Pbintray_apikey=""

script:
  - ./gradlew build -Pbintray_user="" -Pbintray_apikey=""

cache:
  directories:
    - "$HOME/.gradle/caches"
    - "$HOME/.m2"

notifications:
  email: false
