language: java
dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

after_success:
  - ./gradlew cobertura pitest coveralls

script:
  - ./gradlew build

cache:
  directories:
    - "$HOME/.gradle/caches"
    - "$HOME/.m2"

notifications:
  email: false
